# Ansible Inventory for Duli Kubernetes Cluster
# Auto-generated by Terraform - Shared cluster for staging and production
# Do not edit manually - regenerated by 'terraform apply'
#
# Usage:
#   For Kubespray: ansible-playbook -i ansible/inventories/hosts.ini playbooks/kubespray.yml
#   For Helm: ansible-playbook -i ansible/inventories/hosts.ini playbooks/helm_infrastructure.yml

[all]
%{ for cp in control_plane_nodes ~}
${cp.name} ansible_host=${cp.public_ip} ip=${cp.private_ip}
%{ endfor ~}
%{ for worker in worker_nodes ~}
${worker.name} ansible_host=${worker.public_ip} ip=${worker.private_ip}
%{ endfor ~}

[kube_control_plane]
%{ for cp in control_plane_nodes ~}
${cp.name}
%{ endfor ~}

[kube_node]
%{ for worker in worker_nodes ~}
${worker.name}
%{ endfor ~}

[etcd]
%{ for cp in control_plane_nodes ~}
${cp.name}
%{ endfor ~}

[k8s_cluster:children]
kube_control_plane
kube_node

[all:vars]
ansible_user=root
