# Ansible Inventory for Kubernetes Cluster
# Auto-generated by Terraform - Environment: ${environment}
# Do not edit manually - regenerated by 'terraform apply'

[all]
%{ for cp in control_plane_nodes ~}
${cp.name} ansible_host=${cp.public_ip} ip=${cp.private_ip}
%{ endfor ~}
%{ for worker in worker_nodes ~}
${worker.name} ansible_host=${worker.public_ip} ip=${worker.private_ip}
%{ endfor ~}

[kube_control_plane]
%{ for cp in control_plane_nodes ~}
${cp.name}
%{ endfor ~}

[kube_node]
%{ for worker in worker_nodes ~}
${worker.name}
%{ endfor ~}

[etcd]
%{ for cp in control_plane_nodes ~}
${cp.name}
%{ endfor ~}

[k8s_cluster:children]
kube_control_plane
kube_node

[all:vars]
ansible_user=root
ansible_ssh_private_key_file=~/.ssh/duli_${environment}
deploy_env=${environment}
